### ISSUE TITLE
Saving GPU server metrics

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#564]
We want to collect detailed metrics for the entire duration of Round 3. Our initial approach to use Sysdig is not applicable as we have observed that Sysdig is most likely involved in the crash of several machine over Round 1.

My idea is to run a custom python script that collect all the metrics that we want and push them to an ELK platform currently running on my home server. My script is 90% complete and collect many usage metrics including GPU metrics and Challenge metrics (e.g. size of pre-processed data being generated, number of line in the predictions file during inference which could allow to monitor progress given that we require participant to systematically write the prediction to file after processing a subject).

In addition, Bruce is looking into using AWS CloudWatch to monitor the usage metics of the AWS machines.

### Tasks

- [ ] Custom metrics collection script (90% done)
   - [ ] Write script (90% done)
   - [ ] Package and deploy script (e.g. using a Docker container)
- [ ] Configure ELK to collect and organize the data
   - [ ] Send data to Elasticsearch and write raw data to files if required. It is important to conserve the native temporal resolution (e.g. every 5 minutes)
   - [ ] Use Kibana to organize the data and create a dashboard
   - [ ] Write a demo python/R script to show that we can use the data for computing usage statistic (e.g. for the paper)
- [x] AWS GPU-Cloudwatch integation (Issue #562)

**Comment by tschaffter** [comment]
Usage stats including CPU, GPU, etc. have been collected for the training and scoring period of the Validation Phase.
