### ISSUE TITLE
Create a Checklist to send to participant when Round 3 starts

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#565]
The objective is to guide participants into delivering suitable containers that will be used during the Collaborative Phase and later available open source to the community.

### Checklist

- [ ] Refer to the columns of the input files using their name (and not their index)
- [ ] Use the following environmental variable whenever applicable
   - [ ] ...
- [ ] Place all the development files in the directory `/src` of the container
